import type { PortfolioProject } from '../types'

export const portfolioProjects: PortfolioProject[] = [
  {
    id: '1',
    category: 'UI/UX Design',
    title: 'Sunset Stretch & Sip',
    description: 'Golden Hour Farm Experience',
    image: '/assets/images/photo1.png',
    link: 'https://www.loom.com/share/fcd3c850c2f6495497fd2ca8bc477f96',
  },
  {
    id: '2',
    category: 'UI/UX Design',
    title: 'Digital Product Ul Design',
    description: '',
    image: '/assets/images/photo2.png',
    link: 'https://www.loom.com/share/727e1df97dae44ac9ad7b8cef99c914d',
  },
  {
    id: '3',
    category: 'UI/UX Design',
    title: 'Match@Health Desktop',
    description: 'Healthcare Matching Platform',
    image: '/assets/images/photo3.png',
    link: 'https://www.loom.com/share/d5786444918f45339e41d50b16dd733a',
  },
  {
    id: '4',
    category: 'UI/UX Design',
    title: 'Match@Health Mobile',
    description: 'Mobile Healthcare Experience',
    image: '/assets/images/photo5.png',
    link: 'https://www.loom.com/share/901d2ac102a240b6ab54477987c57232',
  },
  {
    id: '5',
    category: 'UI/UX Design',
    title: 'Digital Agency Platform',
    description: 'Creative Business Solutions',
    image: '/assets/images/photo4.png',
    link: 'https://www.loom.com/share/da053af75b394a84aa0893bd36a2cf57',
  },
  {
    id: '6',
    category: 'UI/UX Design',
    title: 'Logo Design System',
    description: 'Modern Brand Identity',
    image: '/assets/images/photo6.png',
    link: 'https://www.loom.com/share/05d44a26667847d1bbb4947bd3716036',
  },
  {
    id: '7',
    category: 'UI/UX Design',
    title: 'BMG',
    description: 'great music greater impact',
    image: '/assets/images/photo7.jpeg',
    link: 'https://www.loom.com/share/05d44a26667847d1bbb4947bd3716036',
  },
  {
    id: '8',
    category: 'UI/UX Design',
    title: 'Unpod System',
    description: 'Unpod System',
    image: '/assets/images/photo8.jpeg',
    link: 'https://www.loom.com/share/627d72cc484c4e73944fe46ff1a85401',
  },
  {
    id: '9',
    category: 'UI/UX Design',
    title: 'Maxwell CPA Review',
    description: 'CPA exam preparation platform with modern UI/UX and responsive website design.',
    image: '/assets/images/photo9.jpeg',
    websiteLink: 'https://maxwellcpareview.com/about',
    loomLink: 'https://www.loom.com/share/30b13a615b0f4669a70bdf6ec6d1815d',
  },
  {
    id: '10',
    category: 'UI/UX Design',
    title: 'Fearless Code',
    description: 'Software development company website focused on clean layouts and developer branding.',
    image: '/assets/images/photo10.jpeg',
    websiteLink: 'https://www.fearlesscode.de/',
    loomLink: 'https://www.loom.com/share/51b6e4905fce4970bca52324748bd005',
  },
  {
    id: '11',
    category: 'UI/UX Design',
    title: 'Expertify',
    description: 'Developer-focused platform with modern design system and smooth user experience.',
    image: '/assets/images/photo11.jpeg',
    websiteLink: 'https://expertify.dev/',
    loomLink: 'https://www.loom.com/share/19940c426eb14037b273c36dbff91832',
  },
  {
    id: '12',
    category: 'UI/UX Design',
    title: 'Nestlé India',
    description: 'Corporate food and beverage brand website with structured navigation and branding.',
    image: '/assets/images/photo12.jpeg',
    websiteLink: 'https://www.nestle.in/',
    loomLink: 'https://www.loom.com/share/e8e04132f76c412ebb055b6c071a4ce5',
  },
  {
    id: '13',
    category: 'UI/UX Design',
    title: 'Cadbury UK',
    description: 'Chocolate brand website featuring interactive product showcases and engaging visuals.',
    image: '/assets/images/photo13.jpeg',
    websiteLink: 'https://www.cadbury.co.uk/',
    loomLink: 'https://www.loom.com/share/d926acc1d21f421794587c35a5b49941',
  },
]

